/*
 * frame del menu principal el cual contiene los accesos a los modulos correspondientes.
 */
package INTERFAZ;

import CLASESBD.Conexion;
import java.sql.SQLException;

/**
 *
 * @author Peter Hansen Lobos
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_GESTION_VTA = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        MENU_REMUNERACION = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        MENU_PEDIDO_STK = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        MENU_SERV_TECT = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem50 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MENU_GERENCIA = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        MENU_INFORMES = new javax.swing.JMenu();
        INFORME_VENTAS = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        INFORME_VENDEDORES = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        INFORME_STOCK = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        INFORME_COMPRAS = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        INFORME_CUENTAS = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        MENU_HERRAMIENTA = new javax.swing.JMenu();
        SMENU_MANTENEDORES = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        MENU_EXIT = new javax.swing.JMenu();
        SMENU_SALIR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setResizable(false);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MENU_GESTION_VTA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_GESTION_VTA.setText("Gestion Venta");
        MENU_GESTION_VTA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu8.setText("Generar Venta");

        jMenuItem7.setText("jMenuItem7");
        jMenu8.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu8.add(jMenuItem8);

        MENU_GESTION_VTA.add(jMenu8);
        MENU_GESTION_VTA.add(jSeparator20);

        jMenu9.setText("jMenu9");

        jMenuItem9.setText("jMenuItem9");
        jMenu9.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem10");
        jMenu9.add(jMenuItem10);

        MENU_GESTION_VTA.add(jMenu9);
        MENU_GESTION_VTA.add(jSeparator21);

        jMenuBar1.add(MENU_GESTION_VTA);

        MENU_REMUNERACION.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_REMUNERACION.setText("Remuneraciones");
        MENU_REMUNERACION.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem11.setText("jMenuItem11");
        jMenu6.add(jMenuItem11);

        MENU_REMUNERACION.add(jMenu6);
        MENU_REMUNERACION.add(jSeparator19);

        jMenu7.setText("jMenu7");

        jMenuItem12.setText("jMenuItem12");
        jMenu7.add(jMenuItem12);

        jMenuItem13.setText("jMenuItem13");
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("jMenuItem14");
        jMenu7.add(jMenuItem14);

        MENU_REMUNERACION.add(jMenu7);
        MENU_REMUNERACION.add(jSeparator18);

        jMenuBar1.add(MENU_REMUNERACION);

        MENU_PEDIDO_STK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_PEDIDO_STK.setText("Pedido Stock");
        MENU_PEDIDO_STK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Comprar Stock");
        MENU_PEDIDO_STK.add(jMenuItem1);
        MENU_PEDIDO_STK.add(jSeparator9);

        jMenuItem2.setText("Buscar Stock Compañia");
        MENU_PEDIDO_STK.add(jMenuItem2);
        MENU_PEDIDO_STK.add(jSeparator11);

        jMenuItem3.setText("jMenuItem3");
        MENU_PEDIDO_STK.add(jMenuItem3);
        MENU_PEDIDO_STK.add(jSeparator12);

        jMenuBar1.add(MENU_PEDIDO_STK);

        MENU_SERV_TECT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_SERV_TECT.setText("Serv Tecnico");
        MENU_SERV_TECT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem4.setText("Ingreso Producto");
        MENU_SERV_TECT.add(jMenuItem4);
        MENU_SERV_TECT.add(jSeparator2);

        jMenuItem5.setText("Gestion Rembolso");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MENU_SERV_TECT.add(jMenuItem5);
        MENU_SERV_TECT.add(jSeparator1);

        jMenuItem6.setText("Consulta Producto");
        MENU_SERV_TECT.add(jMenuItem6);
        MENU_SERV_TECT.add(jSeparator3);

        jMenuItem50.setText("Devolucion Proveedor");
        MENU_SERV_TECT.add(jMenuItem50);
        MENU_SERV_TECT.add(jSeparator4);

        jMenuBar1.add(MENU_SERV_TECT);

        MENU_GERENCIA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_GERENCIA.setText("Gerencia");
        MENU_GERENCIA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem16.setText("jMenuItem16");
        MENU_GERENCIA.add(jMenuItem16);

        jMenuBar1.add(MENU_GERENCIA);

        MENU_INFORMES.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_INFORMES.setText("Informes");
        MENU_INFORMES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        INFORME_VENTAS.setText("Informes Ventas");

        jMenuItem18.setText("Informe por area");
        INFORME_VENTAS.add(jMenuItem18);
        INFORME_VENTAS.add(jSeparator22);

        jMenuItem19.setText("Informe por Sub-Area");
        INFORME_VENTAS.add(jMenuItem19);
        INFORME_VENTAS.add(jSeparator23);

        jMenuItem20.setText("Informe por Mes");
        INFORME_VENTAS.add(jMenuItem20);
        INFORME_VENTAS.add(jSeparator24);

        jMenuItem21.setText("Informe de Rebaja");
        INFORME_VENTAS.add(jMenuItem21);
        INFORME_VENTAS.add(jSeparator25);

        MENU_INFORMES.add(INFORME_VENTAS);
        MENU_INFORMES.add(jSeparator5);

        INFORME_VENDEDORES.setText("Informes Vendedores");

        jMenuItem22.setText("jMenuItem18");
        INFORME_VENDEDORES.add(jMenuItem22);

        jMenuItem23.setText("jMenuItem18");
        INFORME_VENDEDORES.add(jMenuItem23);

        jMenuItem24.setText("jMenuItem18");
        INFORME_VENDEDORES.add(jMenuItem24);

        MENU_INFORMES.add(INFORME_VENDEDORES);
        MENU_INFORMES.add(jSeparator6);

        INFORME_STOCK.setText("Informes Stock");

        jMenuItem25.setText("jMenuItem18");
        INFORME_STOCK.add(jMenuItem25);

        jMenuItem26.setText("jMenuItem18");
        INFORME_STOCK.add(jMenuItem26);

        jMenuItem27.setText("jMenuItem18");
        INFORME_STOCK.add(jMenuItem27);

        MENU_INFORMES.add(INFORME_STOCK);
        MENU_INFORMES.add(jSeparator7);

        INFORME_COMPRAS.setText("Informes Compras");

        jMenuItem28.setText("jMenuItem18");
        INFORME_COMPRAS.add(jMenuItem28);

        jMenuItem29.setText("jMenuItem18");
        INFORME_COMPRAS.add(jMenuItem29);

        jMenuItem30.setText("jMenuItem18");
        INFORME_COMPRAS.add(jMenuItem30);

        MENU_INFORMES.add(INFORME_COMPRAS);
        MENU_INFORMES.add(jSeparator8);

        INFORME_CUENTAS.setText("Informes Cta Cte");

        jMenuItem31.setText("jMenuItem18");
        INFORME_CUENTAS.add(jMenuItem31);

        jMenuItem32.setText("jMenuItem18");
        INFORME_CUENTAS.add(jMenuItem32);

        jMenuItem33.setText("jMenuItem18");
        INFORME_CUENTAS.add(jMenuItem33);

        MENU_INFORMES.add(INFORME_CUENTAS);
        MENU_INFORMES.add(jSeparator10);

        jMenuBar1.add(MENU_INFORMES);

        MENU_HERRAMIENTA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_HERRAMIENTA.setText("Herramientas");
        MENU_HERRAMIENTA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SMENU_MANTENEDORES.setText("Mantenedores");

        jMenuItem15.setText("jMenuItem15");
        SMENU_MANTENEDORES.add(jMenuItem15);

        jMenuItem34.setText("jMenuItem15");
        SMENU_MANTENEDORES.add(jMenuItem34);

        jMenuItem35.setText("jMenuItem15");
        SMENU_MANTENEDORES.add(jMenuItem35);

        jMenuItem36.setText("jMenuItem15");
        SMENU_MANTENEDORES.add(jMenuItem36);

        MENU_HERRAMIENTA.add(SMENU_MANTENEDORES);
        MENU_HERRAMIENTA.add(jSeparator13);

        jMenu10.setText("Maestro Articulo");

        jMenuItem37.setText("jMenuItem15");
        jMenu10.add(jMenuItem37);

        jMenuItem38.setText("jMenuItem15");
        jMenu10.add(jMenuItem38);

        jMenuItem39.setText("jMenuItem15");
        jMenu10.add(jMenuItem39);

        MENU_HERRAMIENTA.add(jMenu10);
        MENU_HERRAMIENTA.add(jSeparator14);

        jMenu17.setText("jMenu10");

        jMenuItem40.setText("jMenuItem15");
        jMenu17.add(jMenuItem40);

        jMenuItem41.setText("jMenuItem15");
        jMenu17.add(jMenuItem41);

        jMenuItem42.setText("jMenuItem15");
        jMenu17.add(jMenuItem42);

        jMenuItem43.setText("jMenuItem15");
        jMenu17.add(jMenuItem43);

        MENU_HERRAMIENTA.add(jMenu17);
        MENU_HERRAMIENTA.add(jSeparator15);

        jMenu19.setText("jMenu10");

        jMenuItem44.setText("jMenuItem15");
        jMenu19.add(jMenuItem44);

        jMenuItem45.setText("jMenuItem15");
        jMenu19.add(jMenuItem45);

        jMenuItem46.setText("jMenuItem15");
        jMenu19.add(jMenuItem46);

        jMenuItem47.setText("jMenuItem15");
        jMenu19.add(jMenuItem47);

        MENU_HERRAMIENTA.add(jMenu19);
        MENU_HERRAMIENTA.add(jSeparator16);

        jMenu20.setText("jMenu10");

        jMenuItem48.setText("jMenuItem15");
        jMenu20.add(jMenuItem48);

        jMenuItem49.setText("jMenuItem15");
        jMenu20.add(jMenuItem49);

        MENU_HERRAMIENTA.add(jMenu20);
        MENU_HERRAMIENTA.add(jSeparator17);

        jMenuBar1.add(MENU_HERRAMIENTA);

        MENU_EXIT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MENU_EXIT.setText("Salir");
        MENU_EXIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MENU_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_EXITActionPerformed(evt);
            }
        });

        SMENU_SALIR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        SMENU_SALIR.setText("Cerrar Aplicativo");
        SMENU_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMENU_SALIRActionPerformed(evt);
            }
        });
        MENU_EXIT.add(SMENU_SALIR);

        jMenuBar1.add(MENU_EXIT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_EXITActionPerformed
       
    }//GEN-LAST:event_MENU_EXITActionPerformed

    private void SMENU_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMENU_SALIRActionPerformed
         try {
            Conexion.connect_off();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_SMENU_SALIRActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new frmMenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu INFORME_COMPRAS;
    private javax.swing.JMenu INFORME_CUENTAS;
    private javax.swing.JMenu INFORME_STOCK;
    private javax.swing.JMenu INFORME_VENDEDORES;
    private javax.swing.JMenu INFORME_VENTAS;
    private javax.swing.JMenu MENU_EXIT;
    private javax.swing.JMenu MENU_GERENCIA;
    private javax.swing.JMenu MENU_GESTION_VTA;
    private javax.swing.JMenu MENU_HERRAMIENTA;
    private javax.swing.JMenu MENU_INFORMES;
    private javax.swing.JMenu MENU_PEDIDO_STK;
    private javax.swing.JMenu MENU_REMUNERACION;
    private javax.swing.JMenu MENU_SERV_TECT;
    private javax.swing.JMenu SMENU_MANTENEDORES;
    private javax.swing.JMenuItem SMENU_SALIR;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables

}
